// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ParseWorkbook
void ParseWorkbook(Rcpp::Environment xlsb_env);
RcppExport SEXP _readxlsb_ParseWorkbook(SEXP xlsb_envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type xlsb_env(xlsb_envSEXP);
    ParseWorkbook(xlsb_env);
    return R_NilValue;
END_RCPP
}
// ParseWorksheet
void ParseWorksheet(Rcpp::Environment xlsb_env, int start_row, int end_row, int start_col, int end_col);
RcppExport SEXP _readxlsb_ParseWorksheet(SEXP xlsb_envSEXP, SEXP start_rowSEXP, SEXP end_rowSEXP, SEXP start_colSEXP, SEXP end_colSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type xlsb_env(xlsb_envSEXP);
    Rcpp::traits::input_parameter< int >::type start_row(start_rowSEXP);
    Rcpp::traits::input_parameter< int >::type end_row(end_rowSEXP);
    Rcpp::traits::input_parameter< int >::type start_col(start_colSEXP);
    Rcpp::traits::input_parameter< int >::type end_col(end_colSEXP);
    ParseWorksheet(xlsb_env, start_row, end_row, start_col, end_col);
    return R_NilValue;
END_RCPP
}
// ParseSharedStrings
void ParseSharedStrings(Rcpp::Environment xlsb_env);
RcppExport SEXP _readxlsb_ParseSharedStrings(SEXP xlsb_envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type xlsb_env(xlsb_envSEXP);
    ParseSharedStrings(xlsb_env);
    return R_NilValue;
END_RCPP
}
// ParseStyles
void ParseStyles(Rcpp::Environment xlsb_env);
RcppExport SEXP _readxlsb_ParseStyles(SEXP xlsb_envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type xlsb_env(xlsb_envSEXP);
    ParseStyles(xlsb_env);
    return R_NilValue;
END_RCPP
}
// TransformContents
Rcpp::DataFrame TransformContents(Rcpp::Environment xlsb_env, int start_row, int end_row, int start_col, int end_col, Rcpp::IntegerVector col_int_types, Rcpp::CharacterVector col_names);
RcppExport SEXP _readxlsb_TransformContents(SEXP xlsb_envSEXP, SEXP start_rowSEXP, SEXP end_rowSEXP, SEXP start_colSEXP, SEXP end_colSEXP, SEXP col_int_typesSEXP, SEXP col_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type xlsb_env(xlsb_envSEXP);
    Rcpp::traits::input_parameter< int >::type start_row(start_rowSEXP);
    Rcpp::traits::input_parameter< int >::type end_row(end_rowSEXP);
    Rcpp::traits::input_parameter< int >::type start_col(start_colSEXP);
    Rcpp::traits::input_parameter< int >::type end_col(end_colSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type col_int_types(col_int_typesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type col_names(col_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(TransformContents(xlsb_env, start_row, end_row, start_col, end_col, col_int_types, col_names));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_readxlsb_ParseWorkbook", (DL_FUNC) &_readxlsb_ParseWorkbook, 1},
    {"_readxlsb_ParseWorksheet", (DL_FUNC) &_readxlsb_ParseWorksheet, 5},
    {"_readxlsb_ParseSharedStrings", (DL_FUNC) &_readxlsb_ParseSharedStrings, 1},
    {"_readxlsb_ParseStyles", (DL_FUNC) &_readxlsb_ParseStyles, 1},
    {"_readxlsb_TransformContents", (DL_FUNC) &_readxlsb_TransformContents, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_readxlsb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
