# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ParseWorkbook <- function(xlsb_env) {
    invisible(.Call(`_readxlsb_ParseWorkbook`, xlsb_env))
}

ParseWorksheet <- function(xlsb_env, start_row = 0L, end_row = 0L, start_col = 0L, end_col = 0L) {
    invisible(.Call(`_readxlsb_ParseWorksheet`, xlsb_env, start_row, end_row, start_col, end_col))
}

ParseSharedStrings <- function(xlsb_env) {
    invisible(.Call(`_readxlsb_ParseSharedStrings`, xlsb_env))
}

ParseStyles <- function(xlsb_env) {
    invisible(.Call(`_readxlsb_ParseStyles`, xlsb_env))
}

TransformContents <- function(xlsb_env, start_row, end_row, start_col, end_col, col_int_types, col_names) {
    .Call(`_readxlsb_TransformContents`, xlsb_env, start_row, end_row, start_col, end_col, col_int_types, col_names)
}

